steps:
- id: 'build-image-flask'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=us.gcr.io/$PROJECT_ID/flaskapp:latest'
    - '--file=Dockerfile'
    - '.'
- id: 'push-image-flask'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker push us.gcr.io/$PROJECT_ID/flaskapp:latest
  wait_for: ['build-image-flask']
substitutions:
    _TESTING: 'test'
options:
    substitution_option: 'ALLOW_LOOSE'
    machineType: 'N1_HIGHCPU_32'
timeout: 80000s
