---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  ports:
    - name: backend
      targetPort: 5000
      port: 80
      protocol: TCP
  selector:
    role: flask-app
